# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    extension_twig:
        class: AppBundle\Twig\Extension\AppBundleExtension
        arguments:  ['@service_container']
        tags:
            - { name: 'twig.extension' }
